/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CertificationIndexRouteImport } from './routes/certification.index'
import { Route as CertificationSlugRouteImport } from './routes/certification.$slug'
import { Route as ContactIndexRouteImport } from './routes/contact.index'
import { Route as ContactEnquiryRouteImport } from './routes/contact.enquiry'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ResourcesCertificateTransferRouteImport } from './routes/resources.certificate-transfer'
import { Route as ResourcesFaqRouteImport } from './routes/resources.faq'
import { Route as ResourcesFurtherTopicsRouteImport } from './routes/resources.further-topics'
import { Route as ResourcesKnowledgeBaseRouteImport } from './routes/resources.knowledge-base'
import { Route as ResourcesSitemapRouteImport } from './routes/resources.sitemap'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as TrainingSlugRouteImport } from './routes/training.$slug'
import { Route as ResourcesBlogIndexRouteImport } from './routes/resources.blog.index'
import { Route as ResourcesBlogSlugRouteImport } from './routes/resources.blog.$slug'
import { Route as ResourcesDownloadsIndexRouteImport } from './routes/resources.downloads.index'
import { Route as ResourcesDownloadsSlugRouteImport } from './routes/resources.downloads.$slug'
import { Route as ResourcesIndustriesIndexRouteImport } from './routes/resources.industries.index'
import { Route as ResourcesIndustriesSlugRouteImport } from './routes/resources.industries.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationIndexRoute = CertificationIndexRouteImport.update({
  id: '/certification/',
  path: '/certification/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationSlugRoute = CertificationSlugRouteImport.update({
  id: '/certification/$slug',
  path: '/certification/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactEnquiryRoute = ContactEnquiryRouteImport.update({
  id: '/contact/enquiry',
  path: '/contact/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCertificateTransferRoute =
  ResourcesCertificateTransferRouteImport.update({
    id: '/resources/certificate-transfer',
    path: '/resources/certificate-transfer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesFaqRoute = ResourcesFaqRouteImport.update({
  id: '/resources/faq',
  path: '/resources/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesFurtherTopicsRoute = ResourcesFurtherTopicsRouteImport.update({
  id: '/resources/further-topics',
  path: '/resources/further-topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesKnowledgeBaseRoute = ResourcesKnowledgeBaseRouteImport.update({
  id: '/resources/knowledge-base',
  path: '/resources/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSitemapRoute = ResourcesSitemapRouteImport.update({
  id: '/resources/sitemap',
  path: '/resources/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingSlugRoute = TrainingSlugRouteImport.update({
  id: '/training/$slug',
  path: '/training/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesBlogIndexRoute = ResourcesBlogIndexRouteImport.update({
  id: '/resources/blog/',
  path: '/resources/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesBlogSlugRoute = ResourcesBlogSlugRouteImport.update({
  id: '/resources/blog/$slug',
  path: '/resources/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesDownloadsIndexRoute = ResourcesDownloadsIndexRouteImport.update({
  id: '/resources/downloads/',
  path: '/resources/downloads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesDownloadsSlugRoute = ResourcesDownloadsSlugRouteImport.update({
  id: '/resources/downloads/$slug',
  path: '/resources/downloads/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndustriesIndexRoute =
  ResourcesIndustriesIndexRouteImport.update({
    id: '/resources/industries/',
    path: '/resources/industries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesIndustriesSlugRoute = ResourcesIndustriesSlugRouteImport.update({
  id: '/resources/industries/$slug',
  path: '/resources/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/careers': typeof CareersRoute
  '/certification/$slug': typeof CertificationSlugRoute
  '/contact/enquiry': typeof ContactEnquiryRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/resources/certificate-transfer': typeof ResourcesCertificateTransferRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/further-topics': typeof ResourcesFurtherTopicsRoute
  '/resources/knowledge-base': typeof ResourcesKnowledgeBaseRoute
  '/resources/sitemap': typeof ResourcesSitemapRoute
  '/training/$slug': typeof TrainingSlugRoute
  '/certification/': typeof CertificationIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
  '/resources/downloads/$slug': typeof ResourcesDownloadsSlugRoute
  '/resources/industries/$slug': typeof ResourcesIndustriesSlugRoute
  '/resources/blog/': typeof ResourcesBlogIndexRoute
  '/resources/downloads/': typeof ResourcesDownloadsIndexRoute
  '/resources/industries/': typeof ResourcesIndustriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/careers': typeof CareersRoute
  '/certification/$slug': typeof CertificationSlugRoute
  '/contact/enquiry': typeof ContactEnquiryRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/resources/certificate-transfer': typeof ResourcesCertificateTransferRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/further-topics': typeof ResourcesFurtherTopicsRoute
  '/resources/knowledge-base': typeof ResourcesKnowledgeBaseRoute
  '/resources/sitemap': typeof ResourcesSitemapRoute
  '/training/$slug': typeof TrainingSlugRoute
  '/certification': typeof CertificationIndexRoute
  '/contact': typeof ContactIndexRoute
  '/training': typeof TrainingIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
  '/resources/downloads/$slug': typeof ResourcesDownloadsSlugRoute
  '/resources/industries/$slug': typeof ResourcesIndustriesSlugRoute
  '/resources/blog': typeof ResourcesBlogIndexRoute
  '/resources/downloads': typeof ResourcesDownloadsIndexRoute
  '/resources/industries': typeof ResourcesIndustriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/careers': typeof CareersRoute
  '/certification/$slug': typeof CertificationSlugRoute
  '/contact/enquiry': typeof ContactEnquiryRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/resources/certificate-transfer': typeof ResourcesCertificateTransferRoute
  '/resources/faq': typeof ResourcesFaqRoute
  '/resources/further-topics': typeof ResourcesFurtherTopicsRoute
  '/resources/knowledge-base': typeof ResourcesKnowledgeBaseRoute
  '/resources/sitemap': typeof ResourcesSitemapRoute
  '/training/$slug': typeof TrainingSlugRoute
  '/certification/': typeof CertificationIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/resources/blog/$slug': typeof ResourcesBlogSlugRoute
  '/resources/downloads/$slug': typeof ResourcesDownloadsSlugRoute
  '/resources/industries/$slug': typeof ResourcesIndustriesSlugRoute
  '/resources/blog/': typeof ResourcesBlogIndexRoute
  '/resources/downloads/': typeof ResourcesDownloadsIndexRoute
  '/resources/industries/': typeof ResourcesIndustriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/careers'
    | '/certification/$slug'
    | '/contact/enquiry'
    | '/legal/$slug'
    | '/resources/certificate-transfer'
    | '/resources/faq'
    | '/resources/further-topics'
    | '/resources/knowledge-base'
    | '/resources/sitemap'
    | '/training/$slug'
    | '/certification/'
    | '/contact/'
    | '/training/'
    | '/resources/blog/$slug'
    | '/resources/downloads/$slug'
    | '/resources/industries/$slug'
    | '/resources/blog/'
    | '/resources/downloads/'
    | '/resources/industries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/careers'
    | '/certification/$slug'
    | '/contact/enquiry'
    | '/legal/$slug'
    | '/resources/certificate-transfer'
    | '/resources/faq'
    | '/resources/further-topics'
    | '/resources/knowledge-base'
    | '/resources/sitemap'
    | '/training/$slug'
    | '/certification'
    | '/contact'
    | '/training'
    | '/resources/blog/$slug'
    | '/resources/downloads/$slug'
    | '/resources/industries/$slug'
    | '/resources/blog'
    | '/resources/downloads'
    | '/resources/industries'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/careers'
    | '/certification/$slug'
    | '/contact/enquiry'
    | '/legal/$slug'
    | '/resources/certificate-transfer'
    | '/resources/faq'
    | '/resources/further-topics'
    | '/resources/knowledge-base'
    | '/resources/sitemap'
    | '/training/$slug'
    | '/certification/'
    | '/contact/'
    | '/training/'
    | '/resources/blog/$slug'
    | '/resources/downloads/$slug'
    | '/resources/industries/$slug'
    | '/resources/blog/'
    | '/resources/downloads/'
    | '/resources/industries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CareersRoute: typeof CareersRoute
  CertificationSlugRoute: typeof CertificationSlugRoute
  ContactEnquiryRoute: typeof ContactEnquiryRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ResourcesCertificateTransferRoute: typeof ResourcesCertificateTransferRoute
  ResourcesFaqRoute: typeof ResourcesFaqRoute
  ResourcesFurtherTopicsRoute: typeof ResourcesFurtherTopicsRoute
  ResourcesKnowledgeBaseRoute: typeof ResourcesKnowledgeBaseRoute
  ResourcesSitemapRoute: typeof ResourcesSitemapRoute
  TrainingSlugRoute: typeof TrainingSlugRoute
  CertificationIndexRoute: typeof CertificationIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
  ResourcesBlogSlugRoute: typeof ResourcesBlogSlugRoute
  ResourcesDownloadsSlugRoute: typeof ResourcesDownloadsSlugRoute
  ResourcesIndustriesSlugRoute: typeof ResourcesIndustriesSlugRoute
  ResourcesBlogIndexRoute: typeof ResourcesBlogIndexRoute
  ResourcesDownloadsIndexRoute: typeof ResourcesDownloadsIndexRoute
  ResourcesIndustriesIndexRoute: typeof ResourcesIndustriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification/': {
      id: '/certification/'
      path: '/certification'
      fullPath: '/certification/'
      preLoaderRoute: typeof CertificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification/$slug': {
      id: '/certification/$slug'
      path: '/certification/$slug'
      fullPath: '/certification/$slug'
      preLoaderRoute: typeof CertificationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/enquiry': {
      id: '/contact/enquiry'
      path: '/contact/enquiry'
      fullPath: '/contact/enquiry'
      preLoaderRoute: typeof ContactEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/certificate-transfer': {
      id: '/resources/certificate-transfer'
      path: '/resources/certificate-transfer'
      fullPath: '/resources/certificate-transfer'
      preLoaderRoute: typeof ResourcesCertificateTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/faq': {
      id: '/resources/faq'
      path: '/resources/faq'
      fullPath: '/resources/faq'
      preLoaderRoute: typeof ResourcesFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/further-topics': {
      id: '/resources/further-topics'
      path: '/resources/further-topics'
      fullPath: '/resources/further-topics'
      preLoaderRoute: typeof ResourcesFurtherTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/knowledge-base': {
      id: '/resources/knowledge-base'
      path: '/resources/knowledge-base'
      fullPath: '/resources/knowledge-base'
      preLoaderRoute: typeof ResourcesKnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/sitemap': {
      id: '/resources/sitemap'
      path: '/resources/sitemap'
      fullPath: '/resources/sitemap'
      preLoaderRoute: typeof ResourcesSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$slug': {
      id: '/training/$slug'
      path: '/training/$slug'
      fullPath: '/training/$slug'
      preLoaderRoute: typeof TrainingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/blog/': {
      id: '/resources/blog/'
      path: '/resources/blog'
      fullPath: '/resources/blog/'
      preLoaderRoute: typeof ResourcesBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/blog/$slug': {
      id: '/resources/blog/$slug'
      path: '/resources/blog/$slug'
      fullPath: '/resources/blog/$slug'
      preLoaderRoute: typeof ResourcesBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/downloads/': {
      id: '/resources/downloads/'
      path: '/resources/downloads'
      fullPath: '/resources/downloads/'
      preLoaderRoute: typeof ResourcesDownloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/downloads/$slug': {
      id: '/resources/downloads/$slug'
      path: '/resources/downloads/$slug'
      fullPath: '/resources/downloads/$slug'
      preLoaderRoute: typeof ResourcesDownloadsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/industries/': {
      id: '/resources/industries/'
      path: '/resources/industries'
      fullPath: '/resources/industries/'
      preLoaderRoute: typeof ResourcesIndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/industries/$slug': {
      id: '/resources/industries/$slug'
      path: '/resources/industries/$slug'
      fullPath: '/resources/industries/$slug'
      preLoaderRoute: typeof ResourcesIndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CareersRoute: CareersRoute,
  CertificationSlugRoute: CertificationSlugRoute,
  ContactEnquiryRoute: ContactEnquiryRoute,
  LegalSlugRoute: LegalSlugRoute,
  ResourcesCertificateTransferRoute: ResourcesCertificateTransferRoute,
  ResourcesFaqRoute: ResourcesFaqRoute,
  ResourcesFurtherTopicsRoute: ResourcesFurtherTopicsRoute,
  ResourcesKnowledgeBaseRoute: ResourcesKnowledgeBaseRoute,
  ResourcesSitemapRoute: ResourcesSitemapRoute,
  TrainingSlugRoute: TrainingSlugRoute,
  CertificationIndexRoute: CertificationIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
  ResourcesBlogSlugRoute: ResourcesBlogSlugRoute,
  ResourcesDownloadsSlugRoute: ResourcesDownloadsSlugRoute,
  ResourcesIndustriesSlugRoute: ResourcesIndustriesSlugRoute,
  ResourcesBlogIndexRoute: ResourcesBlogIndexRoute,
  ResourcesDownloadsIndexRoute: ResourcesDownloadsIndexRoute,
  ResourcesIndustriesIndexRoute: ResourcesIndustriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
